### PR TITLE
Feature/save and load

### PR DESCRIPTION
**Pull request by Minirobbo**
This pull request Implements saving and loading for all the game levels. It also incorporates some changes to the game state, which allow all the required information for the game to be stored in save files. The save directory is set as "save/", but is not added to the git.

**NOTE:** Since this feature has alot of changes with file paths, etc. If this could be reviewed but *NOT MERGED* until after all feature branches have been pushed so that the changes aren't affecting everyone :)

### CODE REVIEW

**Review by connor-golin — APPROVED** [review]
works well as far as I can tell.

not sure if intentional or not but loading causes some entities to not spawn (cage, spawner)

either way I'll still approve since it works

**Review by rowan-gray — APPROVED** [review]
Looks good. Good job.

**Review by AnshulDadhwal — APPROVED** [review]
Looks good to me

**Comment by Minirobbo** [comment]
Merged into main after other feature branches to reduce conflicts

**Pull request merged**
