### PR TITLE
Feature/upgradeplace

### PR DESCRIPTION
**Pull request by VuKhanhVyHo**
Place that can upgrade space ship for minigame

### CODE REVIEW

**Review by Foref — APPROVED** [review]
Ok

**Comment by adamFittlerUQ** [comment]
LGTM

**Comment by VuKhanhVyHo** [comment]
> LGTM

can you approve this pull request for me please

**Review by rowan-gray — APPROVED** [review]
Looks fine

**Review by atharvagupta2003 — APPROVED** [review]

**Review by 86LAK — CHANGES_REQUESTED** [review]
👎

**Review by Manpreetingh — APPROVED** [review]

**Pull request merged**
