### PR TITLE
Feature/storyy

### PR DESCRIPTION
**Pull request by YashMitttal**
Title: "Enhancements for Earth Game Area"

Description:
This pull request encompasses a series of enhancements and updates to the Earth Game Area, improving gameplay and the overall user experience. Here's a summary of the changes included:

1. *Added Test Classes*: We've introduced new test classes to ensure the reliability and stability of the Earth Game Area. These tests cover various aspects of the gameplay to catch any potential issues early on.

2. *Revamped Window Style*: The game's visual aspect has been given a facelift with a revamped window style. This enhances the aesthetics and immersiveness of the Earth Game Area.

3. *Added Dialogues*: To enrich the storytelling aspect of the game, we've integrated new dialogues into the Earth Game. These dialogues contribute to a more engaging narrative and provide players with valuable information.

4. *Generalized DialogueBox and TitleBox Classes*: We've made the codebase more maintainable by generalising the DialogueBox and TitleBox classes. This simplifies the addition of new dialogues and titles throughout the game.

5. *Story Progression*: The Earth Game Area now features a structured story progression. Players will experience a more cohesive narrative as they explore this part of the game.

6. *Controls Screen*: Added a new image for the Controls Screen with buttons. Functionality for those would be added later.

These changes enhance the Earth Game Area's playability, visual appeal, and narrative depth. We welcome your feedback and look forward to merging these improvements into the main branch.

### CODE REVIEW

**Review by RagGul — APPROVED** [review]
All good but please update the javadoc later

**Comment by rike568** [comment]
Just had a look at your branch and when I start the game from the main screen, then exit the game to the main screen, the animation becomes very slow and the main screen buttons change size. Not to sure which file causes this. Need to fix this. Also the upgrade tree button on the game screen overflows the size of the button.

**Comment by aniketgupta17** [comment]
The main screen animation is anyways going to be changed with a new display which will be pushed by Neil , That will resolve the error . The upgrade tree is something we haven't touched , Its the same way in the main. @rike568

**Comment by rike568** [comment]
@aniketgupta17 if you have a look at the text in main for upgrade tree compared to your  text it overflows the button.

**Comment by aniketgupta17** [comment]
> @aniketgupta17 if you have a look at the text in main for upgrade tree compared to your text it overflows the button.

@rike568 We have made the changes and now it works absolutely fine , Please have a look now

**Review by rowan-gray — APPROVED** [review]
Other than the laggy home screen, seems fine to me.

**Review by Tarushi263 — APPROVED** [review]

**Pull request merged**
