### PR TITLE
Feature/brick game

### PR DESCRIPTION
**Pull request by AnshulDadhwal**
Created a basic layout for the new brick game that we will be implementing into the main game. We have created it as a separate standalone game in the main menu and will be looking to integrate it in the next sprint. This sprint we are just focusing on finishing it's core functionalities. Let me know of any changes that need to be made if there is a conflict :p

### CODE REVIEW

**Comment by ArmandoLiebenberg** [comment]
LGTM 👍

**Review by ArmandoLiebenberg — APPROVED** [review]
LGTM

**Review by Minirobbo — COMMENTED** [review]
LGTM once you fix the conflicts.

**Review by Minirobbo — APPROVED** [review]
LGTM once you fix the conflicts.

**Review by rowan-gray — APPROVED** [review]
Looks good to me. Just remove the savefile from the commit.

**Pull request merged**
