### PR TITLE
Feature/companion

### PR DESCRIPTION
**Pull request by atharvagupta2003**
-displayed companion on all maps
-improved laboratory window
-improved powerups
-improved companion movement

### CODE REVIEW

**Review by connor-golin — CHANGES_REQUESTED** [review]
Game crashes selecting the first powerup/potion
Caused by: java.lang.IllegalArgumentException: You must assign a valid PowerupType

**Review by mira-alford — COMMENTED** [review]
There is one test case change im just making before i can approve this.

**Comment by mira-alford** [comment]
> There is one test case change im just making before i can approve this.

Alrighty, i added a testcase that resolves some... issues with your code and other people were running into. Enjoy!

**Review by mira-alford — APPROVED** [review]
LGTM

**Review by connor-golin — APPROVED** [review]

**Comment by connor-golin** [comment]
Ill approve - just make sure those bugs are fixed :)

**Pull request merged**
