### PR TITLE
Feature/obstacle minigame

### PR DESCRIPTION
**Pull request by Foref**
Fixed some asset loading issue due to typos and missing files in EarthGameArea.
Fixed music still playing after exiting Space Obstacle Minigame screen.

### CODE REVIEW

**Review by connor-golin — CHANGES_REQUESTED** [review]
Remove all `to be removed` comments, other than that looks good.

**Comment by Foref** [comment]
done

**Comment by Foref** [comment]
> Remove all `to be removed` comments, other than that looks good.

Removed comments

**Review by connor-golin — APPROVED** [review]

**Comment by connor-golin** [comment]
Fix merge conflicts also

**Pull request merged**
