### PR TITLE
Feature/obstacle minigame merge with main game

### PR DESCRIPTION
**Pull request by Foref**
Fixed some bugs. SpaceGameScreen and ExtractorMinigameScreen have some extra

bugs:
-TerrainFactory map path changed
-asteroid json extra semicolon
-extractor minigame map replaced by earth game map
-adding diaologcomponent after creation of entity, which is a no no. changed to adding them in create() methods of 
npc factory and enemy factory. 
Unresolved bugs, wont crush the game:
-Unknown animation "stand" and "left" not added into atlas

Extra features:
-Space minigame has some extra stuff, mostly just aesthetics, no other method of exit map yet, just the exit button on top right
- Extractor minigame has background with fire. No interactions yet

### CODE REVIEW

**Comment by Foref** [comment]
Added minigame popup window feature when clicking "F" key on keyboard near extractor with X on it in EarthGameArea.

**Comment by Minirobbo** [comment]
@Foref you have merge conflicts to fix...

**Comment by Foref** [comment]
> @Foref you have merge conflicts to fix...

I will reopen and check

**Comment by Foref** [comment]
> @Foref you have merge conflicts to fix...

Merge conflict resolved

**Review by connor-golin — APPROVED** [review]
Seems to work as intended.
Approved

**Pull request merged**
